---
title: Tash Naved
baseURL: "/"
params:
  palette: red
  header:
    title: TN
    tagline: ''
    logo_img: images/logo.png
    bg_img: ''
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
