---
title: Tash Naved
baseURL: "/"
params:
  palette: red
  header:
    title: TASH NAVED
    tagline: ''
    logo_img: ''
    bg_img: ''
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved (Tash Naved)"
    links:
    - text: Twitter
      url: https://twitter.com/lowenergycomic
      new_window: true
    - text: Instagram
      url: https://www.instagram.com/lowenergycomic/
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
